// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVqgJRA-8gFcLR138hEgAxEMTdbOufVUc',
    appId: '1:1038962105470:web:9713b8929530e88b9f0c2f',
    messagingSenderId: '1038962105470',
    projectId: 'fwends-8ce14',
    authDomain: 'fwends-8ce14.firebaseapp.com',
    storageBucket: 'fwends-8ce14.appspot.com',
    measurementId: 'G-6YSP5NXCEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVjS4dtxl9lK-1FQxFVn84FGm9J21sEF4',
    appId: '1:1038962105470:android:b8dc9eaa0201f9069f0c2f',
    messagingSenderId: '1038962105470',
    projectId: 'fwends-8ce14',
    storageBucket: 'fwends-8ce14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNUBOVyZsBNvpx3SHdn-KM6h7XSmJZv1w',
    appId: '1:1038962105470:ios:bba834132ef431349f0c2f',
    messagingSenderId: '1038962105470',
    projectId: 'fwends-8ce14',
    storageBucket: 'fwends-8ce14.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNUBOVyZsBNvpx3SHdn-KM6h7XSmJZv1w',
    appId: '1:1038962105470:ios:bba834132ef431349f0c2f',
    messagingSenderId: '1038962105470',
    projectId: 'fwends-8ce14',
    storageBucket: 'fwends-8ce14.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVqgJRA-8gFcLR138hEgAxEMTdbOufVUc',
    appId: '1:1038962105470:web:c89dd5ebbce6e5009f0c2f',
    messagingSenderId: '1038962105470',
    projectId: 'fwends-8ce14',
    authDomain: 'fwends-8ce14.firebaseapp.com',
    storageBucket: 'fwends-8ce14.appspot.com',
    measurementId: 'G-QSZ519DLKN',
  );
}
